apiVersion: v1
kind: ConfigMap
metadata:
  name: wekadocs-config
  namespace: wekadocs
data:
  app_config.yaml: |
    app:
      name: wekadocs-graphrag-mcp
      version: "0.1.0"
      log_level: INFO
      environment: ${ENVIRONMENT}
    server:
      host: "0.0.0.0"
      port: 8000
      workers: 4
      timeout: 30
    embedding:
      model_name: "sentence-transformers/all-MiniLM-L6-v2"
      dims: 384
      similarity: "cosine"
      multilingual: false
      version: "v1"
    search:
      vector:
        primary: "qdrant"
        dual_write: false
      graph:
        max_depth: 2
        max_results: 100
        timeout: 30
      hybrid:
        vector_weight: 0.7
        graph_weight: 0.3
        top_k: 20
    validator:
      max_depth: 3
      max_label_scans: 2
      max_expand_ops: 5
      timeout_seconds: 30
    cache:
      l1:
        enabled: true
        ttl_seconds: 300
      l2:
        enabled: true
        ttl_seconds: 3600
    rate_limit:
      enabled: true
      requests_per_minute: 60
      burst_size: 10
