apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-worker
  namespace: wekadocs
  labels:
    app: ingestion-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestion-worker
  template:
    metadata:
      labels:
        app: ingestion-worker
    spec:
      containers:
      - name: ingestion-worker
        image: wekadocs-mcp-server:latest
        command: ["python", "-m", "src.ingestion.worker"]
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: NEO4J_URI
          value: "bolt://neo4j:7687"
        - name: NEO4J_USER
          value: "neo4j"
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wekadocs-secrets
              key: neo4j-password
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: QDRANT_URL
          value: "http://qdrant:6333"
        volumeMounts:
        - name: config
          mountPath: /app/config
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: config
        configMap:
          name: wekadocs-config
