apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wekadocs-ingress
  namespace: wekadocs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - wekadocs.example.com
    secretName: wekadocs-tls
  rules:
  - host: wekadocs.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mcp-server
            port:
              number: 8000
