# NOTE: In production, use sealed-secrets or external secrets operator
# These are placeholder values - must be replaced with actual secrets
# pragma: allowlist secret
apiVersion: v1
kind: Secret
metadata:
  name: wekadocs-secrets
  namespace: wekadocs
type: Opaque
stringData:
  neo4j-password: "CHANGE_ME_NEO4J_PASSWORD"  # pragma: allowlist secret
  jwt-secret: "CHANGE_ME_JWT_SECRET_KEY"  # pragma: allowlist secret
  redis-password: "CHANGE_ME_REDIS_PASSWORD"  # pragma: allowlist secret
  github-webhook-secret: "CHANGE_ME_GITHUB_WEBHOOK_SECRET"  # pragma: allowlist secret
